### ISSUE TITLE
Add Eclipse Package Drone to the list

### ISSUE THREAD

**Issue by ctron** [binary-repositories-comparison/binary-repositories-comparison.github.io#4]
I am the main developer on the Eclipse Package Drone Project and I would like to see Package Drone added to the comparison chart. Of course I am willing to help.

Please also see:
- https://www.eclipse.org/package-drone/
- http://packagedrone.org/
- https://github.com/eclipse/packagedrone

**Comment by jbaruch** [comment]
Hey, that sounds awesome. 
Go ahead and shoot a PR with the new column.
